apiVersion: v1
kind: Service
metadata:
  name: {{ include "proton-bridge.fullname" . }}
  labels:
    {{- include "proton-bridge.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "proton-bridge.selectorLabels" . | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.service.smtp.port }}
      targetPort: smtp
      protocol: TCP
    - name: imap
      port: {{ .Values.service.imap.port }}
      targetPort: imap
      protocol: TCP
